Initial pull request
koritcky/dobule_pendulum pull request #1
Opened 2020-04-20 09:09 UTC by koritcky

# Double pendulum simulation

To start simulation run `main.py`.

## Description
This program simulates double pendulum dynamics with different initial parameters like: masses of balls, rods lengths and deflection angles. An interesting phenomena behind this process in a chaos behavior, when initial parameters has a huge influence of the future evolution.

## How does it work
This program has 4 modules in `\modules`:    
- **pendulum.py**  Creates a pendulum instance and calculates its evolution in time solving differential equations with `scipy.integrate.odeint`.  
- **frames.py** For each pendulum on each time step creates a shot with `matplotlib` and save it in `\frames` dir.  
- **window.py** Draw a simple GUI with `tkinter`. And has a function `simulation` that integrates all of the program flow.  
- **gif_player.py** Draw an animation in the `tkinter` window from files  in `\frames`

2020-04-25 09:55 UTC, alexferenets requested changes
В целом всё очень круто

2020-04-25 09:55 UTC, alexferenets commented on modules/window.py
> +    slider_th1 = Slider(window, label="First deflection angle", row=4, column=0, init_val=3 * np.pi / 7, from_=-np.pi, to=np.pi)
Не претендую на объективность, но возможно в градусах вводить удобнее

2020-04-25 09:55 UTC, alexferenets commented on modules/window.py
> +        gif.create_frames()
Давай на время этой долгой операции отображать в UI, что что-то происходит

2020-04-25 09:55 UTC, alexferenets commented on modules/window.py
> +        gif.create_frames()
Мы сейчас помногу раз можем отрисовывать один и тот же слайд при каждом новом запуске. Если относительно предыдущего нажатия изменилось только `Simulation time`, всё равно все слайды будут отрисованы по новой. 
Т.к. каждый слайд однозначно можно задать своей конфигурацией, предлагаю называть файлы каким-нибудь хэшом от своих параметров и не затирать их при каждом новом `Compile` - только при закрытии всего окна. Если есть опасения по количеству нагенерённых файлов, можно ограничить размер кэша чем-нибудь сверху и подчищать по мере необходимости.

2020-04-28 16:35 UTC, koritcky commented on modules/window.py
> +    slider_th1 = Slider(window, label="First deflection angle", row=4, column=0, init_val=3 * np.pi / 7, from_=-np.pi, to=np.pi)
Согласен, сделал градусы в UI

2020-04-28 16:38 UTC, koritcky commented on modules/window.py
> +        gif.create_frames()
Добавил `Progressbar` для трекинга времени симулчции. Мы его как объект отправляем в `create frames` и там он обновляется. Лучше было сделать через потоки, но это нужно было долго разбираться и, судя по комментариям, делать не не через tkinter.

2020-04-28 16:42 UTC, koritcky commented on modules/window.py
> +        gif.create_frames()
Реализовал сохранение файлов в различных папках внутри `\folder`. Название папки - хэш от всех параметров, кроме `sim_time`. При разных `sim_time` мы идем в уже существующую папку. Если новое время меньше максимально выбранного за всю историю запусков, то воспроизводятся анимация до данного времени. Если больше, то дорисовываются оставшиеся файлы (для этого мы сохраняем значения углов и скоростей для на последнем кадре).

2020-05-01 10:56 UTC, alexferenets approved these changes
Зачтено, 2/2

2020-05-04 10:22 UTC, merged